version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:4001/api}
    container_name: laundryku-frontend
    restart: always
    ports:
      - '3001:3001'
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:4001/api}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laundryku-backend
    restart: always
    ports:
      - '4001:4001'
    command: sh -c "npx prisma db push && npm install tsx && npx tsx prisma/seed.ts && node dist/app.js"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DATABASE_URL=postgresql://laundryku:${POSTGRES_PASSWORD:-laundryku_secret_2026}@postgres:5432/laundryku
      - MONGODB_URI=mongodb://mongodb:27017/laundryku_wa
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-super-secret-jwt-laundryku-prod-key}
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3001}
      - SUPERADMIN_EMAIL=${SUPERADMIN_EMAIL:-superadmin@laundryku.com}
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD:-SuperAdmin@2026}
      - SUPERADMIN_NAME=${SUPERADMIN_NAME:-Super Admin}
      - SUPERADMIN_WA_NUMBER=${SUPERADMIN_WA_NUMBER:-6285229925593}
      - WA_SESSION_DIR=${WA_SESSION_DIR:-./wa-sessions}
      - APP_URL=${APP_URL:-http://localhost:4001}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-your-email@gmail.com}
      - SMTP_PASS=${SMTP_PASS:-your-app-password}
      - SMTP_FROM=${SMTP_FROM:-noreply@laundryku.com}
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: laundryku-postgres
    restart: always
    environment:
      POSTGRES_USER: laundryku
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-laundryku_secret_2026}
      POSTGRES_DB: laundryku
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U laundryku']
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: laundryku-mongodb
    restart: always
    volumes:
      - mongodata_prod:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: laundryku-redis
    restart: always
    volumes:
      - redisdata_prod:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata_prod:
  mongodata_prod:
  redisdata_prod:
